In [1]:
import numpy as np

v_row = np.array([1,2,3])

v_col = np.array([[1], [2], [3]])

In [3]:
np.array([[1,2],
        [3,4],
        [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
matrix = np.mat([[1,2],
        [3,4],
        [5,6]])

In [5]:
matrix

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
# Sparse Matrix
zeros = np.array([[0,0,0,0,0,0,0],
                 [0,1,0,0,0,0,0],
                 [3,0,0,0,0,0,0]])

from scipy import sparse
sparse_matrix = sparse.csr_matrix(zeros)

print(sparse_matrix)

  (1, 1)	1
  (2, 0)	3


In [8]:
v = np.array([2,4,6,8,10,12])

v[2]

6

In [9]:
m = np.array([[1,2,3],
             [2,4,6],
             [3,6,9]])

m[1,1]

4

In [10]:
v[3:]

array([ 8, 10, 12])

In [11]:
m[:2, :]

array([[1, 2, 3],
       [2, 4, 6]])

In [12]:
m[:, 1:2]

array([[2],
       [4],
       [6]])

In [13]:
m.shape

(3, 3)

In [14]:
m.size

9

In [17]:
mm = m + 2

In [18]:
np.max(mm), np.min(mm)

(11, 3)

In [19]:
mm

array([[ 3,  4,  5],
       [ 4,  6,  8],
       [ 5,  8, 11]])

In [20]:
np.max(mm, axis=0)

array([ 5,  8, 11])

In [23]:
np.max(mm, axis=1)

array([ 5,  8, 11])

In [30]:
am = np.array([[1,5,3,4],
            [5,6,9,8],
              [9,10,11,12]])

In [31]:
np.max(am, axis=0) #column max

array([ 9, 10, 11, 12])

In [32]:
np.max(am, axis=1) #row max

array([ 5,  9, 12])

In [33]:
np.mean(am)

6.916666666666667

In [34]:
np.var(am)

10.743055555555555

In [35]:
np.std(am)

3.277660073216189

In [36]:
np.mean(am, axis=0) #column

array([5.        , 7.        , 7.66666667, 8.        ])

In [37]:
am.reshape(6,2)

array([[ 1,  5],
       [ 3,  4],
       [ 5,  6],
       [ 9,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
am.reshape(12)

array([ 1,  5,  3,  4,  5,  6,  9,  8,  9, 10, 11, 12])

In [39]:
am

array([[ 1,  5,  3,  4],
       [ 5,  6,  9,  8],
       [ 9, 10, 11, 12]])

In [40]:
am.T

array([[ 1,  5,  9],
       [ 5,  6, 10],
       [ 3,  9, 11],
       [ 4,  8, 12]])

In [41]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [42]:
am.flatten()

array([ 1,  5,  3,  4,  5,  6,  9,  8,  9, 10, 11, 12])

In [43]:
am.reshape(am.size)

array([ 1,  5,  3,  4,  5,  6,  9,  8,  9, 10, 11, 12])

In [45]:
np.linalg.matrix_rank(am) #Linear Algebra

3

In [47]:
am

array([[ 1,  5,  3,  4],
       [ 5,  6,  9,  8],
       [ 9, 10, 11, 12]])

In [46]:
am.diagonal()

array([ 1,  6, 11])

In [49]:
am.diagonal(offset=2)

array([3, 8])

In [50]:
am.diagonal(offset=-1)

array([ 5, 10])

In [51]:
ei = np.array([[1,-1,3],
              [1,1,6],
              [3,8,9]])

eigenvalues, eigenvectors = np.linalg.eig(ei)

In [52]:
eigenvalues, eigenvectors

(array([13.55075847,  0.74003145, -3.29078992]),
 array([[-0.17622017, -0.96677403, -0.53373322],
        [-0.435951  ,  0.2053623 , -0.64324848],
        [-0.88254925,  0.15223105,  0.54896288]]))

In [53]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.dot(a, b)

20

In [54]:
a @ b #Python 3.5+

20

In [55]:
np.add(a,b)

array([3, 5, 7])

In [57]:
np.subtract(b,a)

array([1, 1, 1])

In [58]:
a + b

array([3, 5, 7])

In [59]:
a - b

array([-1, -1, -1])

In [60]:
aa = np.array([[1,1],
              [1,2]])

bb = np.array([[1,3],
              [1,2]])

aa @ bb

array([[2, 5],
       [3, 7]])

In [61]:
# pseudorandom generator
np.random.seed(0)

np.random.random(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [63]:
np.random.seed(0)
np.random.random(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [64]:
np.random.seed(1)
np.random.random(4)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])